"""initial schema

Revision ID: 6580d5f52bed
Revises: 
Create Date: 2026-09-20 19:00:47.812351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6580d5f52bed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('handle', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('learner', 'mentor', 'support', 'staff')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('handle')
    )
    op.create_table('challenges',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Text(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('completion_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('average_attempts_to_pass', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('learning_objectives', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('hints', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("difficulty IN ('Beginner', 'Intermediate', 'Advanced', 'Expert')", name='ck_challenges_difficulty'),
    sa.CheckConstraint("status IN ('published', 'draft', 'archived')", name='ck_challenges_status'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index('ix_challenges_category', 'challenges', ['category'], unique=False)
    op.create_index('ix_challenges_difficulty', 'challenges', ['difficulty'], unique=False)
    op.create_index('ix_challenges_status_created_at', 'challenges', ['status', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('challenge_prerequisites',
    sa.Column('challenge_id', sa.BigInteger(), nullable=False),
    sa.Column('prerequisite_id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('challenge_id <> prerequisite_id', name='ck_challenge_prerequisites_not_self'),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['prerequisite_id'], ['challenges.id'], ),
    sa.PrimaryKeyConstraint('challenge_id', 'prerequisite_id')
    )
    op.create_table('challenge_tags',
    sa.Column('challenge_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('challenge_id', 'tag_id')
    )
    op.create_index('ix_challenge_tags_tag_id', 'challenge_tags', ['tag_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('challenge_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('assignee_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'open'"), nullable=False),
    sa.Column('priority', sa.Text(), server_default=sa.text("'medium'"), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_locked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('view_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("priority IN ('low', 'medium', 'high', 'urgent')", name='ck_conversations_priority'),
    sa.CheckConstraint("status IN ('open', 'answered', 'resolved', 'closed')", name='ck_conversations_status'),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index('ix_conversations_assignee_open', 'conversations', ['assignee_id', 'created_at'], unique=False, postgresql_where=sa.text('resolved_at IS NULL AND deleted_at IS NULL'))
    op.create_index('ix_conversations_challenge_id_created_at', 'conversations', ['challenge_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_conversations_created_at_id', 'conversations', [sa.literal_column('created_at DESC'), sa.literal_column('id DESC')], unique=False)
    op.create_index('ix_conversations_last_activity_at_id', 'conversations', [sa.literal_column('last_activity_at DESC'), sa.literal_column('id DESC')], unique=False)
    op.create_index('ix_conversations_status_created_at', 'conversations', ['status', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('conversation_tags',
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('conversation_id', 'tag_id')
    )
    op.create_index('ix_conversation_tags_tag_id', 'conversation_tags', ['tag_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('posted_as_role', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('upvotes', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('helpful_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_internal', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_accepted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_spoiler', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("posted_as_role IN ('learner', 'mentor', 'support', 'staff')", name='ck_messages_posted_as_role'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'sequence_no', name='uq_messages_conversation_id_sequence_no')
    )
    op.create_index('ix_messages_author_id_created_at', 'messages', ['author_id', 'created_at'], unique=False)
    op.create_index('uq_messages_accepted_per_conversation', 'messages', ['conversation_id'], unique=True, postgresql_where=sa.text('is_accepted'))
    op.create_table('message_reactions',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('upvote', 'helpful')", name='ck_message_reactions_type'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'message_id', 'type')
    )
    op.create_index('ix_message_reactions_message_id', 'message_reactions', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_message_reactions_message_id', table_name='message_reactions')
    op.drop_table('message_reactions')
    op.drop_index('uq_messages_accepted_per_conversation', table_name='messages', postgresql_where=sa.text('is_accepted'))
    op.drop_index('ix_messages_author_id_created_at', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_conversation_tags_tag_id', table_name='conversation_tags')
    op.drop_table('conversation_tags')
    op.drop_index('ix_conversations_status_created_at', table_name='conversations')
    op.drop_index('ix_conversations_last_activity_at_id', table_name='conversations')
    op.drop_index('ix_conversations_created_at_id', table_name='conversations')
    op.drop_index('ix_conversations_challenge_id_created_at', table_name='conversations')
    op.drop_index('ix_conversations_assignee_open', table_name='conversations', postgresql_where=sa.text('resolved_at IS NULL AND deleted_at IS NULL'))
    op.drop_table('conversations')
    op.drop_index('ix_challenge_tags_tag_id', table_name='challenge_tags')
    op.drop_table('challenge_tags')
    op.drop_table('challenge_prerequisites')
    op.drop_index('ix_challenges_status_created_at', table_name='challenges')
    op.drop_index('ix_challenges_difficulty', table_name='challenges')
    op.drop_index('ix_challenges_category', table_name='challenges')
    op.drop_table('challenges')
    op.drop_table('users')
    op.drop_table('tags')
    # ### end Alembic commands ###
